export const PRODUCT_FIELDS = [
  "id",
  "sku",
  "name",
  "slug",
  "brand",
  "manufacturer",
  "part_number",
  "model",
  "category",
  "description",
  "condition",
  "quantity_available",
  "price",
  "currency",
  "listing_type",
  "warehouse_location",
  "lot_id",
  "images",
  "specifications",
  "documents",
  "status",
] as const;

export const LOT_FIELDS = [
  "id",
  "lot_reference",
  "name",
  "description",
  "location",
  "items",
  "total_quantity",
  "condition",
  "images",
  "inventory_file",
  "status",
] as const;

export const EQUIPMENT_FIELDS = [
  "id",
  "reference",
  "manufacturer",
  "model",
  "serial_number",
  "year",
  "operating_hours",
  "condition",
  "location",
  "description",
  "specifications",
  "images",
  "documents",
  "status",
] as const;

export const LEAD_FIELDS = [
  "lead_id",
  "lead_type",
  "product_id",
  "sku",
  "lot_id",
  "company",
  "contact",
  "email",
  "phone",
  "country",
  "quantity",
  "message",
  "source",
  "status",
  "created_at",
] as const;

export const LISTING_TYPES = [
  "Buy Now",
  "Buy or Enquire",
  "Whole Lot",
  "Equipment Enquiry",
] as const;
